(cl:in-package edumip_msgs-msg)
(cl:export '(SETPOINT_PHI_DOT-VAL
          SETPOINT_PHI_DOT
          SETPOINT_GAMMA_DOT-VAL
          SETPOINT_GAMMA_DOT
          SETPOINT_PHI-VAL
          SETPOINT_PHI
          PHI-VAL
          PHI
          SETPOINT_GAMMA-VAL
          SETPOINT_GAMMA
          GAMMA-VAL
          GAMMA
          SETPOINT_THETA-VAL
          SETPOINT_THETA
          THETA-VAL
          THETA
          D1_U-VAL
          D1_U
          D3_U-VAL
          D3_U
          DUTYL-VAL
          DUTYL
          DUTYR-VAL
          DUTYR
          WHEEL_ANGLE_L-VAL
          WHEEL_ANGLE_L
          WHEEL_ANGLE_R-VAL
          WHEEL_ANGLE_R
          BODY_FRAME_EASTING-VAL
          BODY_FRAME_EASTING
          BODY_FRAME_NORTHING-VAL
          BODY_FRAME_NORTHING
          BODY_FRAME_HEADING-VAL
          BODY_FRAME_HEADING
          VBATT-VAL
          VBATT
          ARMED-VAL
          ARMED
          RUNNING-VAL
          RUNNING
))